name: Builder

on: ["push", "pull_request", "workflow_dispatch"]

jobs:
  build:
    name: Build SDH-CSSLoader for Decky
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up NodeJS 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
  
    - name: Install JS dependencies
      run: |
        npm i -g pnpm
        pnpm install
      
    - name: Build Frontend
      run: |
        pnpm run build
    
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: 'build.zip'
        exclusions: '*.git* /*node_modules/* /*assets/* /*src/* package-lock.json .prettierrc pnpm-lock.yaml README.md rollup.config.js tsconfig.json'
      
    - name: Upload package artifact
      uses: actions/upload-artifact@v3
      with:
        name: SDH-CSSLoader-Decky
        path: ./build.zip
    
    - name: Send Zip in discord
      uses: tsickert/discord-webhook@v5.3.0
      if: ${{ github.event_name == 'workflow_dispatch' }}
      with:
        webhook-url: ${{ secrets.WEBHOOK_URL }}
        content: ${{ github.event.head_commit.message }}
        filename: "./build.zip"
  
  build-standalone-win:
    name: Build SDH-CSSLoader Standalone for Windows
    runs-on: windows-2022

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python 3.10.2
      uses: actions/setup-python@v4
      with:
        python-version: "3.10.2"

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller==5.5
        pip install -r requirements.txt
      
    - name: Get inject.py dependency from decky-loader
      run: |
        git clone --depth=1 https://github.com/SteamDeckHomebrew/decky-loader 
        copy ./decky-loader/backend/injector.py injector.py

    - name: Build Python Backend
      run: pyinstaller --noconfirm --onefile --name "CssLoader-Standalone" ./main.py ./injector.py

    - name: Upload package artifact
      uses: actions/upload-artifact@v3
      with:
        name: SDH-CSSLoader-Win-Standalone
        path: ./dist/CssLoader-Standalone.exe